# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the Python code to the container
COPY . .

# Specify the command to run your Python script
CMD ["python", "main3.py"]